export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_SUCCESS= 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAILD = 'FETCH_TASK_FAILD';
export const FILTER_TASK = 'FILTER_TASK';
export const FILTER_TASK_SUCCESS = 'FILTER_TASK_SUCCESS';

export const ADD_TASK_FAILD = 'ADD_TASK_FAILD';
export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const FETCH_TASK_EDITING = 'FETCH_TASK_EDITING';

export const UPDATE_TASK_FAILD = 'UPDATE_TASK_FAILD';
export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';


export const DELETE_TASK_FAILD = 'DELETE_TASK_FAILD';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
